// src/data.js

export const rooms = [
    {
        id: 1,
        name: "Deluxe Room",
        price: 200,
        rating: 4.5,
        features: ["Wi-Fi", "Air Conditioner", "TV", "Room Service"],
        image: "deluxe-room.jpg",
        availableFrom: "2024-09-15",
        availableTo: "2024-09-20",
    },
    {
        id: 2,
        name: "Suite Room",
        price: 400,
        rating: 5,
        features: ["Wi-Fi", "Air Conditioner", "Private Pool", "TV", "Room Service"],
        image: "suite-room.jpg",
        availableFrom: "2024-09-12",
        availableTo: "2024-09-25",
    },
    {
        id: 3,
        name: "Standard Room",
        price: 150,
        rating: 3.8,
        features: ["Wi-Fi", "TV"],
        image: "standard-room.jpg",
        availableFrom: "2024-09-10",
        availableTo: "2024-09-20",
    },
    {
        id: 4,
        name: "Family Suite",
        price: 350,
        rating: 4.7,
        features: ["Wi-Fi", "Air Conditioner", "TV", "Mini Bar", "Room Service"],
        image: "family-suite.jpg",
        availableFrom: "2024-09-20",
        availableTo: "2024-10-05",
    },
    {
        id: 5,
        name: "Penthouse Suite",
        price: 600,
        rating: 5,
        features: ["Wi-Fi", "Air Conditioner", "Private Pool", "TV", "Room Service", "Jacuzzi"],
        image: "penthouse-suite.jpg",
        availableFrom: "2024-09-18",
        availableTo: "2024-10-15",
    },
    {
        id: 6,
        name: "Economy Room",
        price: 100,
        rating: 3.5,
        features: ["Wi-Fi", "TV"],
        image: "economy-room.jpg",
        availableFrom: "2024-09-01",
        availableTo: "2024-09-30",
    },
    {
        id: 7,
        name: "Executive Suite",
        price: 500,
        rating: 4.8,
        features: ["Wi-Fi", "Air Conditioner", "TV", "Private Balcony", "Room Service"],
        image: "executive-suite.jpg",
        availableFrom: "2024-09-25",
        availableTo: "2024-10-10",
    },
    {
        id: 8,
        name: "Garden Room",
        price: 180,
        rating: 4.2,
        features: ["Wi-Fi", "Air Conditioner", "TV", "Garden View"],
        image: "garden-room.jpg",
        availableFrom: "2024-09-10",
        availableTo: "2024-09-30",
    },
    {
        id: 9,
        name: "Ocean View Room",
        price: 250,
        rating: 4.6,
        features: ["Wi-Fi", "Air Conditioner", "TV", "Ocean View"],
        image: "ocean-view-room.jpg",
        availableFrom: "2024-09-15",
        availableTo: "2024-10-05",
    },
    {
        id: 10,
        name: "Luxury Suite",
        price: 700,
        rating: 5,
        features: ["Wi-Fi", "Air Conditioner", "Private Pool", "TV", "Jacuzzi", "Personal Butler"],
        image: "luxury-suite.jpg",
        availableFrom: "2024-09-01",
        availableTo: "2024-10-01",
    }
];